stages:
  - Compliance
  - Build
  - Test
  - Deploy

variables:
  IMAGE_BASE: ${CI_REGISTRY}/kwinft/ci-images/archlinux/kwinft-base

workflow:
  rules:
    - when: always


Message lint:
  stage: Compliance
  image: node:latest
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^Plasma\// || $CI_COMMIT_TAG'
      when: never
    - when: always
  variables:
    UPSTREAM: https://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@${CI_SERVER_HOST}/kwinft/disman.git
  script:
    - if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ];
      then export COMPARE_BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME; else export COMPARE_BRANCH=master; fi
    - "echo Branch to compare: $COMPARE_BRANCH"
    - yarn global add @commitlint/cli
    - yarn add conventional-changelog-conventionalcommits
    - git remote add _upstream $UPSTREAM || git remote set-url _upstream $UPSTREAM
    - git fetch -q _upstream $COMPARE_BRANCH
    - commitlint --verbose --config=ci/compliance/commitlint.config.js --from=_upstream/$COMPARE_BRANCH
  cache:
    paths:
      - node_modules/

clang-format:
  stage: Compliance
  image: ${IMAGE_BASE}-master:latest
  script:
    # Run clang-format via wrapper script.
    - bash ci/compliance/clang-format.sh


.common-master: &common-master
  image: ${IMAGE_BASE}-master:latest
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^Plasma\// || $CI_COMMIT_TAG'
      when: never
    - when: on_success

.common-stable: &common-stable
  image: ${IMAGE_BASE}-stable:latest
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^Plasma\// || $CI_COMMIT_TAG'
      when: on_success
    - when: never


.common-build: &common-build
  stage: Build
  script:
    - mkdir ci-build && cd ci-build
    - cmake
      -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_EXE_LINKER_FLAGS=--coverage
      -DCMAKE_INSTALL_PREFIX:PATH=/usr ../
    - make -j$(nproc)
    - make install -j$(nproc)
  artifacts:
    paths:
      - ci-build
    expire_in: 1 week

Master build:
  <<: *common-build
  <<: *common-master

Stable build:
  <<: *common-build
  <<: *common-stable


.common-test-script: &common-test-script
  - cd ci-build
  - Xvfb :1 -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &
  - export DISPLAY=:1
  - export WAYLAND_DEBUG=1 MESA_DEBUG=1 LIBGL_DEBUG=verbose
  - export QT_LOGGING_RULES="*=true"
  - ctest -N
  - dbus-run-session ctest --output-on-failure

Master autotests:
  stage: Test
  needs:
    - job: Master build
      artifacts: true
  <<: *common-master
  script:
    - *common-test-script
    # Coverage report created from source dir with build dir exluded (MOC files etc.).
    # First invokation for the GitLab pipeline regex, second for GitLab pages publishing.
    - cd ..
    - gcovr -e ci-build -e tests -r . ci-build
    - mkdir coverage-html-output
    - gcovr --html-details coverage-html-output/coverage.html -e ci-build -e tests -r . ci-build
  artifacts:
    paths:
      - coverage-html-output
    expire_in: 1 week

Stable autotests:
  stage: Test
  needs:
    - job: Stable build
      artifacts: true
  <<: *common-stable
  script:
    - *common-test-script


pages:
  stage: Deploy
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "kwinft" && $CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
  needs:
    - job: Master autotests
      artifacts: true
  script:
    - mv coverage-html-output public
  artifacts:
    paths:
      - public
    expire_in: 1 week
