# SPDX-FileCopyrightText: 2024 Roman Gilg <subdiff@gmail.com>
# SPDX-License-Identifier: MIT
name: Main Checks
on:
  - push
  - pull_request
jobs:
  message-lint:
    uses: ./.github/workflows/commit-lint.yml
    with:
      upstream-repo: winft/disman

  clang-format:
    uses: ./.github/workflows/clang-format.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/frameworks-master

  install:
    uses: ./.github/workflows/install.yml
    needs: build
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/frameworks-master

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/frameworks-master

  package:
    uses: ./.github/workflows/package.yml
    needs: build
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/frameworks-master
      package-name: disman
